# Set Current Directory
setwd(file.path(Sys.getenv("OneDriveCommercial"), "Documents", "aiPolicy", "scripts"))

# AI Bills 2019-2020 ####
aiBills2019_2020 <- list(
    ## SB348 ####
    SB348 = list(
        id = "SB-348",
        type = "Senate Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 348,
        title = "Department of Technology: artificial intelligence: strategic plans",
        date = "2019-02-19",
        description = "An act to add Chapter 6 (commencing with Section 12897) to Part 2.5 of Division 3 of Title 2 of the Government Code, relating to state government.",
        sponsor = "Chang, Ling Ling",
        party = "Republican",
        district = 29,
        sponsorUrl = "https://ballotpedia.org/Ling_Ling_Chang",
        digest = "Existing law establishes within the Government Operations Agency the Department of Technology, which is supervised by the Director of Technology, who also serves as the State Chief Information Officer. Existing law authorizes the director and the department to exercise various powers in creating and managing the information technology policy of the state. Existing law requires the director, among other duties, to establish and enforce state information technology strategic plans, policies, standards, and enterprise architecture.
        This bill would require the Director of Technology and the Director of Motor Vehicles to each devise a strategic plan, as specified, to utilize artificial intelligence technology designed to aid departments and agencies with the incorporation of artificial intelligence into state information technology strategic plans, policies, standards, and enterprise architecture to improve state services. The bill would encourage the Governor to appoint a special adviser on artificial intelligence to create a statewide strategic plan, as specified, to utilize artificial technology to improve state services. The bill also would encourage certain entities to designate a chief artificial intelligence officer.",
        tldr = "Existing law governs the Department of Technology's role in managing state IT policy. This bill proposes that the Directors of Technology and Motor Vehicles create strategic plans to integrate AI into state IT policies to enhance services. It also suggests appointing an AI advisor for a statewide strategy and encourages organizations to designate a chief AI officer.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SB348&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SB348",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SB348",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SB348",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SB348&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SB348",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SB348",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SB348&version=20190SB34897AMD",
        file = "20190SB348_97.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Government", "Technology"),
        aiType = "General AI",
        aiSector = "Government",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Supportive",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## SJR6 ####
    SJR6 = list(
        id = "SJR-6",
        type = "Senate Joint Resolution",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 6,
        title = "Artificial intelligence",
        date = "2019-07-09",
        description = "Relative to artificial intelligence.",
        sponsor = "Chang, Ling Ling",
        party = "Republican",
        district = 29,
        sponsorUrl = "https://archive.senate.ca.gov/member-archives/2019-20/ling-ling-chang-r-district-29",
        digest = "This measure would urge the President and the Congress of the United States to develop a comprehensive Artificial Intelligence Advisory Committee and to adopt a comprehensive artificial intelligence policy.",
        tldr = "This measure calls on the President and Congress to establish an Artificial Intelligence Advisory Committee and adopt a comprehensive AI policy.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SJR6&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SJR6",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SJR6",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SJR6",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SJR6&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SJR6",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SJR6",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SJR6&version=20190SJR697CHP",
        file = "20190SJR6_97.pdf",
        measureOutcome = "Chaptered",
        measureStage = "Chaptered",
        measureBill = "Chaptered by Secretary of State - Res. Chapter 112, Statutes of 2019",
        measureVote = "No Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Non-Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Federal Policy", "Comprehensive Artificial Intelligence Advisory Committee", "Artificial Intelligence Policy"),
        aiType = "General AI",
        aiSector = "Federal",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB459 ####
    AB459 = list(
        id = "AB-459",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 459,
        title = "State government: Artificial Intelligence in State Government Services Commission: report",
        date = "2019-02-11",
        description = "An act to add and repeal Section 11820.50 of the Government Code, relating to state government.",
        sponsor = "Kiley, Kevin",
        party = "Republican",
        district = 6,
        sponsorUrl = "https://ballotpedia.org/Kevin_Kiley",
        digest = "Existing law establishes within the Government Operations Agency the Department of Technology under the supervision of the Director of Technology, who also serves as the State Chief Information Officer. The department is generally responsible for the approval and oversight of information technology projects by, among other things, consulting with state agencies during initial project planning to ensure that project proposals are based on well-defined programmatic needs.
        This bill would require the Artificial Intelligence in State Government Services Commission, which would be established if AB 976 of the 2018–19 Regular Session is enacted, to report to the Legislature on the commission’s recommended minimum standards for the use of artificial intelligence that includes specified information, including fostering accountability in state government services and prioritizing the safety and security of artificial intelligence technologies used by state government. The bill would make its operation contingent on the enactment of AB 976 of the 2018–19 Regular Session on or before January 1, 2020, and establishes the artificial intelligence commission described above.",
        tldr = "This bill would establish the Artificial Intelligence in State Government Services Commission to report to the Legislature on minimum standards for AI use in state government services.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB459&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB459",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB459",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB459",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB459&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB459",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB459",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB459&version=20190AB45997AMD",
        file = "20190AB459_97.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "State Government", "Technology"),
        aiType = "General AI",
        aiSector = "Government",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB1576 ####
    AB1576 = list(
        id = "AB-1576",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 1576,
        title = "Secretary of Government Operations: working group: technology",
        date = "2019-02-22",
        description = "An act to add and repeal Section 11547.5 of the Government Code, relating to technology.",
        sponsor = "Calderon, Ian C.",
        party = "Democrat",
        district = 57,
        sponsorUrl = "https://ballotpedia.org/Ian_Charles_Calderon",
        digest = "Existing law provides that there is a Government Operations Agency governed by the Secretary of Government Operations. Existing law establishes, within the Government Operations Agency, the Department of Technology under the supervision of the Director of Technology, who also serves as the State Chief Information Officer. The department is generally responsible for the approval and oversight of information technology projects by, among other things, consulting with state agencies during initial project planning to ensure that project proposals are based on well-defined programmatic needs. Under existing law, there is, in the Government Operations Agency, the Department of General Services, which shall develop and enforce policy and procedures and institute or cause the institution of those investigations and proceedings as it deems proper to assure effective operation of all functions performed by the department and to conserve the rights and interests of the state.
        This bill would require the Secretary of Government Operations to appoint participants to an artificial intelligence working group on or before July 1, 2020. The bill would require the composition of the working group to be representative of California’s demographic and cultural diversity. For purposes of these provisions, the bill would define artificial intelligence technology. The bill would require the working group to evaluate the uses, risks, benefits, and legal implications associated with the development and deployment of artificial intelligence by California-based businesses. The bill would require the working group to recommend best practices for the development and deployment of artificial intelligence by California-based businesses for specified purposes. The bill would require the working group, on or before July 1, 2021, to report to the Legislature on the evaluations and recommendations described in the previous sentence. The bill would repeal these provisions on January 1, 2023.",
        tldr = "This bill would require the Secretary of Government Operations to appoint an AI working group to evaluate AI uses, risks, benefits, and legal implications for California-based businesses.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB1576&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB1576",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB1576",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB1576",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB1576&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB1576",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB1576",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB1576&version=20190AB157695AMD",
        file = "20190AB1576_95.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Technology", "Working Group", "Diversity"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB976 ####
    AB976 = list(
        id = "AB-976",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 976,
        title = "Artificial Intelligence in State Government Services Commission",
        date = "2019-02-01",
        description = "An act to add and repeal Chapter 8.3 (commencing with Section 11820.10) to of Part 1 of Division 3 of Title 2 of the Government Code, relating to state government.",
        sponsor = "Chau, Ed",
        party = "Democrat",
        district = 49,
        sponsorUrl = "https://ballotpedia.org/Edwin_Chau",
        digest = "Existing law establishes, within the Government Operations Agency, the Department of Technology under the supervision of the Director of Technology, who also serves as the State Chief Information Officer. The department is generally responsible for the approval and oversight of information technology projects by, among other things, consulting with state agencies during initial project planning to ensure that project proposals are based on well-defined programmatic needs.
        This bill would establish in state government the Artificial Intelligence in State Government Services Commission comprised of 8 members, as specified, and would require the advisory commission to annually convene a public process to gather input on how artificial intelligence and data science could be used to improve state services. This bill would require the commission to propose a plan for soliciting artificial intelligence and data science related demonstration projects for critical state services and incorporating successful artificial intelligence and data science related demonstration projects into existing state government services. The bill would require the commission to establish guiding principles for the proposed plan on or before November 1, 2020. The bill would require the commission to submit its recommendations based on input gathered from the public process to the Legislature and the Governor by November 1, 2021, and by November 1 of every year thereafter. The bill would make related findings and declarations. The bill would repeal its provisions on January 1, 2025.",
        tldr = "This bill would establish the Artificial Intelligence in State Government Services Commission to gather input on AI and data science for state services.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB976&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB976",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB976",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB976",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB976&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB976",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB976",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB976&version=20190AB97698AMD",
        file = "20190AB976_98.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "State Government", "Technology", "Data Science", "Annual Review"),
        aiType = "General AI",
        aiSector = "Government",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB594 ####
    AB594 = list(
        id = "AB-594",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 594,
        title = "Artificial intelligence",
        date = "2019-02-14",
        description = "An act to add Section 11546.11 to the Government Code, relating to artificial intelligence.",
        sponsor = "Salas, Rudy",
        party = "Democrat",
        district = 32,
        sponsorUrl = "https://ballotpedia.org/Rudy_Salas",
        digest = "Existing law establishes within the Government Operations Agency the Department of Technology, which is supervised by the Director of Technology, who also serves as the State Chief Information Officer. Existing law authorizes the director and the department to exercise various powers in creating and managing the information technology policy of the state. Existing law requires the director, among other duties, to establish and enforce state information technology strategic plans, policies, standards, and enterprise architecture. Existing law also requires the department to be responsible for the approval and oversight of information technology projects, as specified.
        Executive Order No. N-11-19 established the Future of Work Commission whose primary mission is to study, understand, analyze, and make recommendations regarding, among other things, the impact of technology on work, workers, employers, jobs, and society, as well as methods of promoting better job quality, wages, and working conditions through technology. The executive order requires the commission to, among other things, compile research and best practices from other states and countries on how to deploy technology to benefit workers and the public good, and to develop tools to assess the impact of proposed technologies and evaluate their costs and benefits to workers, employers, the public, and the state.
        This bill would authorize the director to designate a position within the department to evaluate the uses of artificial intelligence in state government and to advise the Director of Technology on incorporating artificial intelligence into state information technology strategic plans, policies, standards, and enterprise architecture. The bill would require the department, in consultation with relevant stakeholders, and in consideration of the recommendations of the Future of Work Commission, to adopt guidelines by January 1, 2021, to govern the use and implementation of artificial intelligence technologies in state government functions. The bill would require the guidelines to include, but not be limited to, standards for, among other things, identifying projects and project components to increase efficiency.",
        tldr = "This bill would authorize the Department of Technology to evaluate AI uses in state government and advise on incorporating AI into state IT strategic plans.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB594&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB594",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB594",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB594",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB594&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB594",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB594",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB594&version=20190AB59495ENR",
        file = "20190AB594_95.pdf",
        measureOutcome = "Failed",
        measureStage = "Enrolled",
        measureBill = "Inactive Bill - Vetoed",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "State Government", "Technology", "Workforce", "Future of Work Commission"),
        aiType = "General AI",
        aiSector = "Government",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## SB730 ####
    SB730 = list(
        id = "SB-730",
        type = "Senate Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 730,
        title = "Commission on Tech Equity",
        date = "2019-02-22",
        description = "An act to add and repeal Chapter 3.7 (commencing with Section 8299) of Division 1 of Title 2 of the Government Code, relating to employment development.",
        sponsor = "Stern, Henry",
        party = "Democrat",
        district = 27,
        sponsorUrl = "https://ballotpedia.org/Henry_Stern",
        digest = "Existing law establishes various advisory boards and commissions in state government with specified duties and responsibilities.
        Existing law requires the Governor to transmit to the Legislature, no later than April 15 of each year, an economic report to be designated as the “Economic Report of the Governor” setting forth, among other things, a review of economic developments during the preceding calendar year and forecasts of trends in employment, income, and investment for the coming year and trends in such major economic sectors as it is feasible to project.
        This bill, until January 1, 2025, would establish in state government the advisory Commission on Tech Equity, which would consist of 6 7 appointed members, as specified, and the Director of the Governor’s Office of Business and Economic Development and the Director of Finance serving as ex officio members. The bill would require the commission to develop recommendations on a policy framework to manage the development, deployment, regulation, taxation, and fair distribution of the benefits of innovation and technology, as specified, and submit the recommendations to the Legislature and to the Governor no later than January 1, 2021, and annually on or before January 1, thereafter.",
        tldr = "This bill would establish the Commission on Tech Equity to develop recommendations on managing innovation, technology, and the benefits of technology.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SB730&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SB730",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SB730",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SB730",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SB730&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SB730",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SB730",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SB730&version=20190SB73095AMD",
        file = "20190SB730_95.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Technology", "Equity", "Innovation", "Policy Framework", "Reporting", "Economic Development"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## SB444 ####
    SB444 = list(
        id = "SB-444",
        type = "Senate Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 444,
        title = "University of California: Berkeley and Irvine law schools: Pro Se Indigent Litigant Research Program",
        date = "2019-02-21",
        description = "An act to add Article 7.9 (commencing with Section 92685) to Chapter 6 of Part 57 of Division 9 of Title 3 of the Education Code, relating to the University of California.",
        sponsor = "Umberg, Tom",
        party = "Democrat",
        district = 34,
        sponsorUrl = "https://ballotpedia.org/Tom_Umberg",
        digest = "Existing law establishes the University of California, under the administration of the Regents of the University of California, as one of the segments of public postsecondary education in this state. The University of California comprises 10 campuses, located at Berkeley, Davis, Irvine, Los Angeles, Merced, Riverside, San Diego, San Francisco, Santa Barbara, and Santa Cruz. The University of California operates law schools at campuses in Berkeley, Davis, Irvine, Los Angeles, and San Francisco.
        This bill would request the regents to enact, no later than July 1, 2021, a resolution to authorize the university’s Berkeley and Irvine law schools, in consultation with the superior courts of the Counties of Alameda and Orange, respectively, to participate in a research program to develop artificial intelligence or machine-learning solutions to address issues of access to justice faced by pro se indigent litigants who are residents of those counties.
        The bill would require each participating law school, no later than March 31, 2024, to submit to specified public officials copies of a report including its findings and recommendations relating to the goals, challenges, successes, and potential areas of growth and development with respect to the research program.",
        tldr = "This bill would request the University of California's Berkeley and Irvine law schools to develop AI solutions to address access to justice for pro se indigent litigants.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SB444&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SB444",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SB444",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SB444",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SB444&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SB444",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SB444",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SB444&version=20190SB44494AMD",
        file = "20190SB444_94.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Access to Justice", "Pro Se Litigants", "University of California", "Law Schools"),
        aiType = "General AI",
        aiSector = "Education",
        aiSubsector = "Research",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB156 ####
    AB156 = list(
        id = "AB-156",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 156,
        title = "Optometrists: endorsement fee",
        date = "2019-01-07",
        description = "An act to amend Section 3152 of the Business and Professions Code, relating to healing arts.",
        sponsor = "Voepel, Randy",
        party = "Republican",
        district = 71,
        sponsorUrl = "https://ballotpedia.org/Randy_Voepel",
        digest = "The Optometry Practice Act provides for the licensure and regulation of the practice of optometry by the State Board of Optometry, which is within the Department of Consumer Affairs. Existing law requires various fees for purposes of the act, and requires those moneys to be deposited in the Optometry Fund.
        This bill would establish an endorsement fee of $50, and would authorize the board to increase the fee to not more than $100.",
        tldr = "This bill would establish an endorsement fee for optometrists.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB156&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB156",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB156",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB156",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB156&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB156",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB156",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB156&version=20190AB15698AMD",
        file = "20190AB156_98.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Non-Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Optometry", "Healing Arts", "Licensure", "Regulation"),
        aiType = "General AI",
        aiSector = "Healthcare",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Low",
        aiImpact = "Low",
        aiEthics = "Low",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Low",
        lastUpdated = "2025-03-17"
    ),
    ## AB3317 ####
    AB3317 = list(
        id = "AB-3317",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 3317,
        title = "Unfair and deceptive practices",
        date = "2019-02-21",
        description = "An act to amend Section 1770 of the Civil Code, relating to unfair business practices.",
        sponsor = "Wicks, Buffy",
        party = "Democrat",
        district = 15,
        sponsorUrl = "https://ballotpedia.org/Buffy_Wicks",
        digest = "Existing law, the Consumer Legal Remedies Act, makes unlawful specified unfair methods of competition and unfair or deceptive acts or practices undertaken by any person in a transaction intended to result or which results in the sale or lease of goods or services to any consumer.
        This bill would provide that, for purposes of specified unfair methods of competition and unfair or deceptive acts or practices that a person who provides data, information, and content to a business is a customer in a transaction.
        This bill would make it an unfair or deceptive practice for an online platform operator to fail to act in accordance with its community guidelines, terms and conditions, content management policies, content management features, or other promises that are presented to users of the online platform, as defined. The bill would also make it an unfair or deceptive practice for an online platform operator to use design, code, or artificial intelligence to modify or manipulate a user interface with the purpose or substantial effect of, among other things, cultivating compulsive usage, as defined, or obscuring, subverting, or impairing user autonomy, decisionmaking, or choice to obtain user data. The bill would require an online platform to provide a public reporting tool to flag instance of banned designs. The bill would require that public reporting tool to contain publically viewable reports. The bill would authorize the Attorney General, at their discretion, to release guidance for compliance.",
        tldr = "This bill would make it an unfair or deceptive practice for an online platform operator to fail to act in accordance with its community guidelines, terms and conditions, content management policies, content management features, or other promises that are presented to users of the online platform.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB3317&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB3317",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB3317",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB3317",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB3317&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB3317",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB3317",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB3317&version=20190AB331798AMD",
        file = "20190AB3317_98.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Consumer Protection", "Online Platforms", "Unfair Practices", "Artificial Intelligence"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "High",
        aiImpact = "High",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "High",
        aiTransparency = "High",
        lastUpdated = "2025-03-17"
    ),
    ## ACR125 ####
    ACR125 = list(
        id = "ACR-125",
        type = "Assembly Concurrent Resolution",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 125,
        title = "Bias and discrimination in hiring reduction through new technology",
        date = "2019-08-14",
        description = "Relative to employment.",
        sponsor = "Jones-Sawyer, Reginald",
        party = "Democrat",
        district = 57,
        sponsorUrl = "https://ballotpedia.org/Reginald_Jones-Sawyer",
        digest = "his measure would urge policymakers in both federal and state government to explore ways to promote the development and use of new technologies to reduce bias and discrimination in hiring and help reduce discrimination in employment in California, as provided.",
        tldr = "This measure would urge policymakers in both federal and state government to explore ways to promote the development and use of new technologies to reduce bias and discrimination in hiring and help reduce discrimination in employment in California.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200ACR125&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200ACR125",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200ACR125",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200ACR125",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200ACR125&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200ACR125",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200ACR125",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200ACR125&version=20190ACR12598AMD",
        file = "20190ACR125_98.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "No Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Non-Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Employment", "Bias", "Discrimination", "Hiring", "Technology"),
        aiType = "General AI",
        aiSector = "Human Resources",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "High",
        aiImpact = "High",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "High",
        aiTransparency = "High",
        lastUpdated = "2025-03-17"
    ),
    ## SCR13 ####
    SCR13 = list(
        id = "SCR-13",
        type = "Senate Concurrent Resolution",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 13,
        title = "International Women’s Day",
        date = "2019-03-27",
        description = "Relative to International Women’s Day.",
        sponsor = "Jackson, Hannah-Beth",
        party = "Democrat",
        district = 19,
        sponsorUrl = "https://ballotpedia.org/Hannah-Beth_Jackson",
        digest = "This measure designates March 8, 2019, as International Women’s Day.",
        tldr = "This measure designates March 8, 2019, as International Women’s Day.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SCR13&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SCR13",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SCR13",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SCR13",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SCR13&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SCR13",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SCR13",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SCR13&version=20190SCR1397CHP",
        file = "20190SCR13_97.pdf",
        measureOutcome = "Chaptered",
        measureStage = "Chaptered",
        measureBill = "Chaptered by Secretary of State. Res. Chapter 22, Statutes of 2019",
        measureVote = "No Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Non-Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("International Women’s Day", "Artificial Intelligence"),
        aiType = "General AI",
        aiSector = "Human Resources",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Low",
        aiImpact = "Low",
        aiEthics = "Low",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Low",
        lastUpdated = "2025-03-17"
    ),
    ## AB2269 ####
    AB2269 = list(
        id = "AB-2269",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 2269,
        title = "Personal rights: automated decision systems",
        date = "2020-02-14",
        description = "An act to add Title 1.81.8 (commencing with Section 1798.400) to Part 4 of Division 3 of the Civil Code, relating to automatic decision systems.",
        sponsor = "Chau, Ed",
        party = "Democrat",
        district = 49,
        sponsorUrl = "https://ballotpedia.org/Ed_Chau",
        digest = "Existing law establishes the Department of Business Oversight in the Business, Consumer Services, and Housing Agency, headed by the Commissioner of Business Oversight. Under existing law, the department has charge of the execution of specified laws relating to various financial institutions and financial services.
        Existing law, the California Fair Employment and Housing Act, protects and safeguards the right and opportunity of all persons to seek, obtain, and hold employment without discrimination, abridgment, or harassment on account of race, religious creed, color, national origin, ancestry, physical disability, mental disability, medical condition, genetic information, marital status, sex, gender, gender identity, gender expression, age, sexual orientation, or military and veteran status.
        Existing law regulates the use of personal information, including the California Consumer Privacy Act of 2018, which grants a consumer various rights with regard to personal information relating to that consumer that is held by a business. The act requires a business that collects personal information about a consumer to disclose the consumer’s right to delete personal information in a form that is reasonably accessible to consumers and in accordance with a specified process.
        This bill would enact the Automated Decision Systems Accountability Act of 2020. The bill would require a business in California that provides a person, as defined, with a program or device that uses an automated decision system (ADS) to take affirmative steps to ensure that there are processes in place to continually test for biases during the development and usage of the ADS, conduct an ADS impact assessment on its program or device to determine whether the ADS has a disproportionate adverse impact on a protected class, as specified, examine if the ADS in question serves reasonable objectives and furthers a legitimate interest, and compare the ADS to alternatives or reasonable modifications that may be taken to limit adverse consequences on protected classes. The bill would require a business, by March 1, 2022, and annually thereafter, to submit a report to the Department of Business Oversight summarizing the results of its ADS impact assessment for each program or device that uses an ADS. The bill would also require a business, if it makes any significant modification to an ADS, to reconduct an ADS impact assessment under these circumstances.
        The bill would require the department, by January 1, 2022, to develop a procedure for businesses to use in making the required reports and to make general information on the reporting process available on its internet website. The bill would require the department, if a business fails to comply with these procedures, to send a written notice to the business regarding its failure to comply, and would require the business to submit the report within 60 days of the date of that notice. The bill would make violations of these provisions subject to a civil penalty.
        The bill would also require the department, by March 1, 2022, to establish an Automated Decision Systems Advisory Task Force, composed of various representatives from the public and private sectors, for the purpose of reviewing and providing advice on the use of automated decision systems in businesses, government, and various other settings.",
        tldr = "This bill would require a business in California that provides a person with a program or device that uses an automated decision system (ADS) to take affirmative steps to ensure that there are processes in place to continually test for biases during the development and usage of the ADS.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB2269&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB2269",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB2269",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB2269",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB2269&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB2269",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB2269",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB2269&version=20190AB226999INT",
        file = "20190AB2269_99.pdf",
        measureOutcome = "Failed",
        measureStage = "Introduced",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Automated Decision Systems", "Bias", "Discrimination", "Accountability", "California Consumer Privacy Act"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "High",
        aiImpact = "High",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "High",
        aiTransparency = "High",
        lastUpdated = "2025-03-17"
    ),
    ## SB752 ####
    SB752 = list(
        id = "SB-752",
        type = "Senate Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 752,
        title = "The California Master Plan on Tech Equity",
        date = "2019-02-22",
        description = "An act to add and repeal Chapter 3.7 (commencing with Section 8299) to of Division 1 of Title 2 of the Government Code, relating to state government.",
        sponsor = "Stern, Henry",
        party = "Democrat",
        district = 27,
        sponsorUrl = "https://ballotpedia.org/Henry_Stern",
        digest = "Existing law establishes various advisory boards and commissions in state government with specified duties and responsibilities. 
        This bill would create, until  November 30, 2024, the Commission on Tech Equity consisting of 6 appointed members, as specified. specified, and the Secretary of Labor and Workforce Development and the Controller serving as ex officio members. The bill would require the commission to, commission, among other duties, to convene a public process to gather input and to understand the economic, social, workplace, and technological landscape of innovation and technology in California.",
        tldr = "This bill would create the Commission on Tech Equity to convene a public process to gather input and to understand the economic, social, workplace, and technological landscape of innovation and technology in California.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200SB752&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200SB752",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200SB752",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200SB752",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200SB752&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200SB752",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200SB752",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200SB752&version=20190SB75297AMD",
        file = "20190SB752_97.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Technology", "Equity", "Innovation", "Policy Framework", "Reporting", "Economic Development"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Moderate",
        aiImpact = "Moderate",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Moderate",
        lastUpdated = "2025-03-17"
    ),
    ## AB485 ####
    AB485 = list(
        id = "AB-485",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 485,
        title = "Local government: economic development subsidies",
        date = "2019-03-15",
        description = "An act to add Section 53083.1 to the Government Code, relating to local government.",
        sponsor = "Medina, Jose",
        party = "Democrat",
        district = 61,
        sponsorUrl = "https://ballotpedia.org/Jose_Medina",
        digest = "Existing law requires each local agency, as defined, to provide specified information to the public before approving an economic development subsidy within its jurisdiction, and to, among other things, hold hearings and report on those subsidies, as provided. Existing law defines “economic development subsidy” for these purposes to mean any expenditure of public funds or loss of revenue to a local agency in the amount of $100,000 or more, for the purpose of stimulating economic development within the jurisdiction of a local agency, as provided. 
        This bill, on and after January 1, 2020, would similarly require each local agency to provide specified information to the public before approving an economic development subsidy for a warehouse distribution center, as defined, and to, among things, hold hearings and report on those subsidies, as provided. The bill would require local agencies to submit a report to the Governor’s Office of Business and Economic Development providing specified information and would require the office to make those reports available to the public through its internet website. The bill would require a warehouse distribution center to provide a local agency any information necessary to comply with these provisions. 
        The bill would prohibit a local agency from signing a nondisclosure agreement regarding a warehouse distribution center as part of negotiations or in the contract for any economic development subsidy. 
        The bill would declare that its provisions address a matter of statewide concern rather than a municipal affair and, therefore, apply to all cities, including charter cities. 
        The California Constitution requires local agencies, for the purpose of ensuring public access to the meetings of public bodies and the writings of public officials and agencies, to comply with a statutory enactment that amends or enacts laws relating to public records or open meetings and contains findings demonstrating that the enactment furthers the constitutional requirements relating to this purpose. This bill would make legislative findings to that effect.",
        tldr = "This bill would require each local agency to provide specified information to the public before approving an economic development subsidy for a warehouse distribution center.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB485&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB485",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB485",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB485",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB485&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB485",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB485",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB485&version=20190AB48595CHP",
        file = "20190AB485_95.pdf",
        measureOutcome = "Chaptered",
        measureStage = "Chaptered",
        measureBill = "Chaptered by Secretary of State. Chapter 803, Statutes of 2019",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Artificial Intelligence", "Local Government", "Economic Development", "Subsidies"),
        aiType = "General AI",
        aiSector = "Government",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Neutral",
        aiAccountability = "Low",
        aiImpact = "Low",
        aiEthics = "Low",
        aiInnovation = "Low",
        aiPrivacy = "Low",
        aiTransparency = "Low",
        lastUpdated = "2025-03-17"
    ),
    ## AB3339 ####
    AB3339 = list(
        id = "AB-3339",
        type = "Assembly Bill",
        body = "California Legislature",
        session = "2019-2020 Regular Session",
        no = 3339,
        title = "Kids Internet Design and Safety Act",
        date = "2020-02-21",
        description = "An act to add Title 1.81.7 (commencing with Section 1798.300) to Part 4 of Division 3 of the Civil Code, relating to business.",
        sponsor = "WIcks, Buffy",
        party = "Democrat",
        district = 15,
        sponsorUrl = "https://ballotpedia.org/Buffy_Wicks",
        digest = "Existing law grants consumers certain rights in regard to businesses, as defined, that collect personal information about them, including the right to know what information is collected and the right to opt-out of the sale of that information. Existing law prohibits a business from selling personal information of consumers that the business knows are 16 years of age or younger unless that sale is affirmatively authorized.
        This bill would enact the Kids Internet Design and Safety Act for purposes of keeping children safe and protecting their interests on the internet. The bill would prohibit an operator of a platform directed to children, as defined, from incorporating certain features on any of its platforms, including, but not limited to, an auto-play setting that, without input from a covered user, as defined, commences additional video content directly following the video content initially selected by the user. The bill would prohibit an operator of a platform directed to children, or a platform for which the operator has constructive knowledge that covered users use the platform, from engaging in certain activities, including amplifying, promoting, or encouraging covered users’ consumption of videos or other forms of content that involve sexual material or other dangerous, abusive, exploitative, or wholly commercial content. The bill would also prohibit an operator of a platform directed to children from engaging in certain activities, including directing content that includes host-selling, as defined, to covered users. The bill would provide that a violation of the act constitutes unfair competition.
        This bill would require an operator of a platform to only use age verification information collected from covered users for age verification purposes. The bill would require the Attorney General to promulgate, by January 1, 2026, specified regulations relating to the act, including an annual audit process for purposes of evaluating the level of compliance with the act. The bill would require the annual audit to be conducted for 25 platforms that are directed to children and that have the highest total number of covered users in the past calendar year. The bill would require the first annual audit to be completed by no later than January 1, 2027. The bill would also make related findings and declarations.",
        tldr = "This bill would prohibit an operator of a platform directed to children from incorporating certain features on any of its platforms, including an auto-play setting that commences additional video content directly following the video content initially selected by the user.",
        text = "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201920200AB3339&search_keywords=artificial+intelligence",
        votes = "https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201920200AB3339",
        history = "https://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201920200AB3339",
        billAnalysis = "https://leginfo.legislature.ca.gov/faces/billAnalysisClient.xhtml?bill_id=201920200AB3339",
        todaysLaw = "https://leginfo.legislature.ca.gov/faces/billCompareClient.xhtml?bill_id=201920200AB3339&showamends=false",
        compareVersions = "https://leginfo.legislature.ca.gov/faces/billVersionsCompareClient.xhtml?bill_id=201920200AB3339",
        status = "https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201920200AB3339",
        pdf = "https://leginfo.legislature.ca.gov/faces/billPdf.xhtml?bill_id=201920200AB3339&version=20190AB333998AMD",
        file = "20190AB3339_98.pdf",
        measureOutcome = "Failed",
        measureStage = "Amended Assembly",
        measureBill = "Inactive Bill - Died",
        measureVote = "Majority Vote Required",
        measureAppropriation = "Non-Appropriation",
        measureFiscal = "Fiscal Committee",
        measureLocal = "Non-State-Mandated Local Program",
        measureUrgency = "Non-Urgency",
        measureTax = "Non-Tax Levy",
        tags = list("Children", "Internet Safety", "Design", "Artificial Intelligence"),
        aiType = "General AI",
        aiSector = "Technology",
        aiSubsector = "Policy",
        aiDomain = "AI Integration",
        aiDisposition = "Restrictive",
        aiAccountability = "High",
        aiImpact = "High",
        aiEthics = "Significant",
        aiInnovation = "Low",
        aiPrivacy = "High",
        aiTransparency = "High",
        lastUpdated = "2025-03-17"
    )
)


# Save the AI Bills list ####

# Change the directory to the data path
setwd(file.path(Sys.getenv("OneDriveCommercial"), "Documents", "aiPolicy", "data"))

# Save the AI Bills R data list
save(aiBills2019_2020, file = file.path("aiBills2019_2020.RData"))

# Load the AI Bills list ####
load(file.path("aiBills2019_2020.RData"))

# Export the AI Bills to a json file ####
library("jsonlite")
aiBills2019_2020.json <- toJSON(aiBills2019_2020, pretty = TRUE, auto_unbox = TRUE)
write(aiBills2019_2020.json, file = "aiBills2019-2020.json")
